


import argparse
import os.path
import sys
import tensorflow as tf

import returnn.TFUtil as tfu
import pickle

def create_support_dict(graph_def):
    device_dic = {}
    name2id_dic = {}
    id2name_dic = {}
    id = 0
    for node in graph_def.node:
      op = str(node.op)
      name2id_dic[str(node.name)] = id
      id2name_dic[id] = str(node.name)
      id+=1
      device_dic[str(node.name)] = [str(x) for x in tfu.supported_devices_for_op(op)]
    with open('supported_device.txt', 'wb') as dict_items_save:
      pickle.dump(device_dic, dict_items_save)
    with open('name2id.txt','wb') as name2iddict:
      pickle.dump(name2id_dic, name2iddict)
    with open('id2name.txt','wb') as id2namedict:
      pickle.dump(id2name_dic, id2namedict)


graph_def = tf.GraphDef()
def main(args):
    for event in tf.train.summary_iterator(args.filepath):
        tag = False
        for graph in event.graph_def:
                graph_def.ParseFromString(event.graph_def)
                tag = True
                break
        if tag:
            break
    print ("Graph is loaded")

    create_support_dict(graph_def)   

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument(
      '--filepath',
      type=str,
      required=True,
      help='input event....local file. it is the log file generated by tensorflow for tensorboard.'
  )
  args = parser.parse_args()
  main(args)


